"""Add SubscriptionDuration Table for balance managemnt

Revision ID: 0cc4ce6093cd
Revises: 3dfc9a5be8ed
Create Date: 2024-02-20 23:25:29.301971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc4ce6093cd'
down_revision: Union[str, None] = '3dfc9a5be8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
