"""Add SubscriptionDuration Table for balance managemnt

Revision ID: eaf535410ebd
Revises: 3dfc9a5be8ed
Create Date: 2024-02-21 00:14:21.229709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf535410ebd'
down_revision: Union[str, None] = '3dfc9a5be8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_durations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('duration_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(op.f('fk_subscriptions_duration_id_subscription_durations'), 'subscriptions', 'subscription_durations', ['duration_id'], ['id'])
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_subscriptions_duration_id_subscription_durations'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'duration_id')
    op.drop_table('subscription_durations')
    # ### end Alembic commands ###
